### ISSUE TITLE
it only support pyarrow 3.0.0

### ISSUE THREAD

**Issue by alitrack** [dmitrykoval/vinum#12]
if not installed pyarrow or installed pyarrow version >3.0 will get 

```
>>> import vinum as vn
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/steven/anaconda3/envs/vinum/lib/python3.8/site-packages/vinum/__init__.py", line 20, in <module>
    import vinum_lib
ImportError: dlopen(/Users/steven/anaconda3/envs/vinum/lib/python3.8/site-packages/vinum_lib.cpython-38-darwin.so, 2): Library not loaded: @rpath/libarrow.300.dylib
  Referenced from: /Users/steven/anaconda3/envs/vinum/lib/python3.8/site-packages/vinum_lib.cpython-38-darwin.so
  Reason: image not found

```

**Comment by dmitrykoval** [comment]
Hey Steven, thanks for the report! The pyarrow version dependency is indeed outdated and will be updated soon. Thanks again.
